steps:  
- id: 'Docker Build'
  name: gcr.io/cloud-builders/docker
  dir: 'Stresser_Unit/'
  args: [
    'build', 
    '-t', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/artifact-repository/stresser-unit:$REVISION_ID',
     '-t',
     'us-central1-docker.pkg.dev/$PROJECT_ID/artifact-repository/stresser-unit:latest',
     '.'
   ]

- id: 'Push to Google ACR'
  name: gcr.io/cloud-builders/docker
  args: [
    'push', 
    'us-central1-docker.pkg.dev/$PROJECT_ID/artifact-repository/stresser-unit:$REVISION_ID'
  ]

# Push the image to Google Container Registry with the latest tag
images: [
    'us-central1-docker.pkg.dev/$PROJECT_ID/artifact-repository/stresser-unit:$REVISION_ID'
  ]
